### ISSUE TITLE
Uncaught TypeError: 'NoneType' object is not iterable


### ISSUE THREAD

**Issue by SKS210375** [PANOimagen/profiletool#26]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 88, in <lambda>
    lambda index: self.plotProfil())
  File "C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 224, in plotProfil
    for profile in self.profiles:
TypeError: 'NoneType' object is not iterable

```
profiletool 4.1.6, QGIS 3.6.2-Noosa on Windows 10

**Comment by JaviBecerra** [comment]
Hi @SKS210375,

Could you provide some context to reproduce your error? I guess that you intended to add something to your First, Second and Third steps... :)
Regards
