### ISSUE TITLE
Qgis 3.8.1 Error message on updating profile tool

### ISSUE THREAD

**Issue by ThomasStruller** [PANOimagen/profiletool#31]
Hallo,
I'm using QGis 3.8.1. On updating your profile tool I got this error message. Your tool doesn't work anymore and has to be deinstalled.

Error message:
ImportError: cannot import name 'getConfigOption' from 'profiletool.pyqtgraph' (C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\__init__.py) 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\__init__.py", line 28, in classFactory
    from .profileplugin import ProfilePlugin
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\profileplugin.py", line 42, in 
    from .tools.profiletool_core import ProfileToolCore
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 45, in 
    from .plottingtool import PlottingTool
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\plottingtool.py", line 45, in 
    from ..pyqtgraph import exporters
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\exporters\__init__.py", line 1, in 
    from .Exporter import Exporter
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\exporters\Exporter.py", line 4, in 
    from ..GraphicsScene import GraphicsScene
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\GraphicsScene\__init__.py", line 1, in 
    from .GraphicsScene import *
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\GraphicsScene\GraphicsScene.py", line 5, in 
    from .. import functions as fn
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\functions.py", line 16, in 
    from . import getConfigOption, setConfigOptions
ImportError: cannot import name 'getConfigOption' from 'profiletool.pyqtgraph' (C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\__init__.py)

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.8.1-Zanzibar Zanzibar, dcd95cc648 

Python-Pfad:
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour
C:/OSGEO4~1/apps/qgis/./python
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlrd-1.2.0-py2.py3-none-any.whl
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlwt-1.3.0-py2.py3-none-any.whl
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\FeatureGridCreator
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
W:/Nuernberg_Sandreuth/2016308/maps

**Comment by Venomasso** [comment]
I have the same problem

mportError: cannot import name 'getConfigOption' from 'profiletool.pyqtgraph' (C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\__init__.py) 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\__init__.py", line 28, in classFactory
    from .profileplugin import ProfilePlugin
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\profileplugin.py", line 42, in 
    from .tools.profiletool_core import ProfileToolCore
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 45, in 
    from .plottingtool import PlottingTool
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\plottingtool.py", line 45, in 
    from ..pyqtgraph import exporters
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\exporters\__init__.py", line 1, in 
    from .Exporter import Exporter
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\exporters\Exporter.py", line 4, in 
    from ..GraphicsScene import GraphicsScene
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\GraphicsScene\__init__.py", line 1, in 
    from .GraphicsScene import *
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\GraphicsScene\GraphicsScene.py", line 5, in 
    from .. import functions as fn
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\functions.py", line 16, in 
    from . import getConfigOption, setConfigOptions
ImportError: cannot import name 'getConfigOption' from 'profiletool.pyqtgraph' (C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\__init__.py)


Versione Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versione di QGIS: 3.4.10-Madeira Madeira, 3d97aaae88 

Percorso Python:
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python
C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Corrado/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by cesarcorreo** [comment]
Same error with QGIS 3.8.1.......

No se pudo cargar el complemento 'profiletool' debido a un error al llamar a su método classFactory() 

ImportError: cannot import name 'getConfigOption' from 'profiletool.pyqtgraph' (C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\__init__.py) 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\__init__.py", line 28, in classFactory
    from .profileplugin import ProfilePlugin
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\profileplugin.py", line 42, in 
    from .tools.profiletool_core import ProfileToolCore
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 45, in 
    from .plottingtool import PlottingTool
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\plottingtool.py", line 45, in 
    from ..pyqtgraph import exporters
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\exporters\__init__.py", line 1, in 
    from .Exporter import Exporter
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\exporters\Exporter.py", line 4, in 
    from ..GraphicsScene import GraphicsScene
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\GraphicsScene\__init__.py", line 1, in 
    from .GraphicsScene import *
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\GraphicsScene\GraphicsScene.py", line 5, in 
    from .. import functions as fn
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\functions.py", line 16, in 
    from . import getConfigOption, setConfigOptions
ImportError: cannot import name 'getConfigOption' from 'profiletool.pyqtgraph' (C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\pyqtgraph\__init__.py)


Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versión de QGIS: 3.8.1-Zanzibar Zanzibar, dcd95cc648 

Ruta de Python:
C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python
C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\qgis-otb-plugin
C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.8\bin\python37.zip
C:\PROGRA~1\QGIS3~1.8\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib
C:\Program Files\QGIS 3.8\bin
C:\Users\usuario\AppData\Roaming\Python\Python37\site-packages
C:\PROGRA~1\QGIS3~1.8\apps\Python37
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\Pythonwin
C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ClosestPoint
C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlrd-1.2.0-py2.py3-none-any.whl
C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlwt-1.3.0-py2.py3-none-any.whl
C:\Users\usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\FeatureGridCreator
C:/Users/usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GroupPointsWithinDistance
C:\Users\usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\shapetools\ext-libs

**Comment by JaviBecerra** [comment]
Thanks for reporting. We updated pyqtgraph to solve a couple issues and it seems that somehow we managed to mess it up in the process :/
We are checking it now, will be back with a fix ASAP.

**Comment by JaviBecerra** [comment]
It seems that the plugin version distributed by QGIS has an empty pyqtgraph\__init__.py file. Unfortunately we do not have the zip we uploaded to QGIS anymore so that we can not verify what went wrong (however the upload process is quite straightforward, we download a zip from github and upload it to QGIS, not really sure how we could have managed to empty a file in the process...).

We have uploaded a revised zip to QGIS, that should be working fine right now if you choose to reinstall the plugin from the plugin manager.
Please let us know if everything is working fine again.

**Comment by cesarcorreo** [comment]
I already downloaded a version of the plugin from Githhub and it works fine.
Thanks for your fast answer and solution.
*________________*


*César Herrera Lindo <http://www.cesarpagina.com>*

**Comment by ThomasStruller** [comment]
Hallo,

I reinstalled the plugin and it works fine now. Thank you very much for
fixing the error.

Ciao
Thomas
