### ISSUE TITLE
Problemas con MetaSearch y Quickmapservices en QGis 3.8

### ISSUE THREAD

**Issue by andresrob** [PANOimagen/profiletool#33]
No se donde enviar la consulta pero mi problema es el siguiente:

Desde que instale versiones superiores a 3.4 aparece el siguiente error y no me deja utilizar el Quickmapservice

Quisiera saber como solucionarlo ya que he desintalado varias veces e instalado distintas versiones y el problema sigue apareciendo

No se pudo cargar el complemento 'MetaSearch' debido a un error al llamar a su método classFactory()

OSError: [Errno 9] Bad file descriptor

Traceback (most recent call last):
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/OSGeo4W64/apps/qgis/./python/plugins\MetaSearch\__init__.py", line 29, in classFactory
    from MetaSearch.plugin import MetaSearchPlugin
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/OSGeo4W64/apps/qgis/./python/plugins\MetaSearch\plugin.py", line 34, in 
    from MetaSearch.dialogs.maindialog import MetaSearchDialog
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/OSGeo4W64/apps/qgis/./python/plugins\MetaSearch\dialogs\maindialog.py", line 50, in 
    from owslib.csw import CatalogueServiceWeb # spellok
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W64\apps\Python37\lib\site-packages\owslib\csw.py", line 27, in 
    from owslib.util import OrderedDict
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W64\apps\Python37\lib\site-packages\owslib\util.py", line 32, in 
    import requests
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W64\apps\Python37\lib\site-packages\requests\__init__.py", line 112, in 
    from . import utils
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W64\apps\Python37\lib\site-packages\requests\utils.py", line 26, in 
    from ._internal_utils import to_native_string
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W64\apps\Python37\lib\site-packages\requests\_internal_utils.py", line 11, in 
    from .compat import is_py2, builtin_str, str
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W64\apps\Python37\lib\site-packages\requests\compat.py", line 61, in 
    from http.cookies import Morsel
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "", line 983, in _find_and_load
  File "", line 967, in _find_and_load_unlocked
  File "", line 677, in _load_unlocked
  File "", line 724, in exec_module
  File "", line 859, in get_code
  File "", line 917, in get_data
OSError: [Errno 9] Bad file descriptor

Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Versión de QGIS: 3.8.2-Zanzibar Zanzibar, 4470baa1a3

Ruta de Python:

    C:/OSGeo4W64/apps/qgis/./python
    C:/Users/Andres/AppData/Roaming/QGIS/QGIS3\profiles\default/python
    C:/Users/Andres/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
    C:/OSGeo4W64/apps/qgis/./python/plugins
    C:\Program Files\Hexagon\ERDAS IMAGINE 2015\usr\lib\Win32Release\python
    C:\OSGeo4W64\bin\python37.zip
    C:\OSGeo4W64\apps\Python37\DLLs
    C:\OSGeo4W64\apps\Python37\lib
    C:\OSGeo4W64\bin
    C:\OSGeo4W64\apps\Python37
    C:\OSGeo4W64\apps\Python37\lib\site-packages
    C:\OSGeo4W64\apps\Python37\lib\site-packages\win32
    C:\OSGeo4W64\apps\Python37\lib\site-packages\win32\lib
    C:\OSGeo4W64\apps\Python37\lib\site-packages\Pythonwin
    C:/Users/Andres/AppData/Roaming/QGIS/QGIS3\profiles\default/python

No se pudo cargar el complemento 'quick_map_services'

ModuleNotFoundError: No module named 'quick_map_services'

Traceback (most recent call last):
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'quick_map_services'

Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Versión de QGIS: 3.8.2-Zanzibar Zanzibar, 4470baa1a3

Ruta de Python:

    C:/OSGeo4W64/apps/qgis/./python
    C:/Users/Andres/AppData/Roaming/QGIS/QGIS3\profiles\default/python
    C:/Users/Andres/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
    C:/OSGeo4W64/apps/qgis/./python/plugins
    C:\Program Files\Hexagon\ERDAS IMAGINE 2015\usr\lib\Win32Release\python
    C:\OSGeo4W64\bin\python37.zip
    C:\OSGeo4W64\apps\Python37\DLLs
    C:\OSGeo4W64\apps\Python37\lib
    C:\OSGeo4W64\bin
    C:\OSGeo4W64\apps\Python37
    C:\OSGeo4W64\apps\Python37\lib\site-packages
    C:\OSGeo4W64\apps\Python37\lib\site-packages\win32
    C:\OSGeo4W64\apps\Python37\lib\site-packages\win32\lib
    C:\OSGeo4W64\apps\Python37\lib\site-packages\Pythonwin
    C:/Users/Andres/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by JaviBecerra** [comment]
(Spanish answer below, please use English in this forum if you can)
Hi, 
How is your problem related to profiletool? It is not mentioned on your description of the issue and we have not been able to reproduce it in a windows machine running QGIS 3.6 with "MetaSearch Catalog Client", "Profiletool" and "QuickMapServices" installed and active.
(There is a chance that entry 'C:\Program Files\Hexagon\ERDAS IMAGINE 2015\usr\lib\Win32Release\python' in your python path is messing something up in your installation anyway).
------
Hola,
¿Cómo has relacionado tu problema con el plugin Profiletool? No hay ninguna referencia en tu descripción ni en las rutas de error, y no hemos podido reproducirlo en una máquina con QGIS 3.6 y los plugins "MetaSearch Catalog Client", "Quick Map Services" y "Profiletool" instalados.
(¿Quizás tu problema está relacionado con la carpeta 'C:\Program Files\Hexagon\ERDAS IMAGINE 2015\usr\lib\Win32Release\python' que aparece en tu ruta de Python?)
