### ISSUE TITLE
Error if a layer is removed while using profile tool

### ISSUE THREAD

**Issue by AlisterH** [PANOimagen/profiletool#45]
While using the profile tool, remove one of the raster layers from the QGIS project.  Then when you click in the map to create your section you get an error like this:
```
2020-06-16T13:34:48     WARNING    Traceback (most recent call last):
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\ptmaptool.py", line 116, in leftClicked
              self.profiletool.updateProfil(self.pointstoDraw)
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 178, in updateProfil
              if self.dockwidget.mdl.item(i,5).data(QtCore.Qt.EditRole).type() == qgis.core.QgsMapLayer.VectorLayer :
             AttributeError: 'QObject' object has no attribute 'type'
```

**Comment by nicogodet** [comment]
@RobertoPanoi closed by #50
