### ISSUE TITLE
AttributeError: 'QObject' object has no attribute 'type'

### ISSUE THREAD

**Issue by jorgealmerio** [PANOimagen/profiletool#66]
Hi, friend,

When I close or open another project from Qgis after I has added a Point layer to Profile Tool I got this error! (Traceback below)

If I remove the point layer from the Profile tool the error does NOT happens !

I am using Windows 10 and I have tested it on Qgis 3.18 e 3.20.3.

Anyway, Thanks for this the plugin!

Jorge Almerio

2021-09-24T10:31:01     WARNING    Traceback (most recent call last):
              File "C:\Users/jorgealmerio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 109, in 
              self.instance.layersRemoved.connect(lambda: self.removeClosedLayers(self.dockwidget.mdl))
              File "C:\Users/jorgealmerio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 282, in removeClosedLayers
              self.dockwidget.removeLayer(i)
              File "C:\Users/jorgealmerio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\ui\ptdockwidget.py", line 331, in removeLayer
              self.profiletoolcore.updateProfil(self.profiletoolcore.pointstoDraw, False, True)
              File "C:\Users/jorgealmerio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 180, in updateProfil
              if self.dockwidget.mdl.item(i, 5).data(QtCore.Qt.EditRole).type() == qgis.core.QgsMapLayer.VectorLayer:
             AttributeError: 'QObject' object has no attribute 'type'

**Comment by nicogodet** [comment]
which version of profiletool ?

**Comment by jorgealmerio** [comment]
Version 4.2.1

**Comment by nicogodet** [comment]
I can't reproduce (I was sure I fixed this bug...)

Could you describe step by step to reproduce the issue ?

**Comment by jorgealmerio** [comment]
1) Open Qgis
2) Open a Qgis project with at least one MDT (Raster) and a Profilable point layer
3) Add the MDT to the profile tool Widget using the "Add Layer" button
4) Add the Profilable point layer to the profile tool Widget using the "Add Layer" button
5) Open another Qgis project

**Comment by nicogodet** [comment]
That's exactly what I've done and no issue :thinking:

**Comment by jorgealmerio** [comment]
I will try to record a video later if you want.

Sorry about that

**Comment by nicogodet** [comment]
If you can, please.

**Comment by jorgealmerio** [comment]
Sorry for take so long!
Please tell me if the attached screenrecord resolution is enough to check it!

https://user-images.githubusercontent.com/16169268/135650080-fdc9aa10-de4e-483c-a40c-7e297d90d9f3.mp4

**Comment by nicogodet** [comment]
I had this issue recently too.

I don't have time to work on this now and it's not a major issue, you can still use both QGIS and profiletool. 
I don't know when I could fix this.
