### ISSUE TITLE
QGIS 3.22.7 Crashes on ProfileTool 4.2.2

### ISSUE THREAD

**Issue by urabbani** [PANOimagen/profiletool#79]
Profiletool 4.2.2 crashes QGIS 3.22.7 on Ubuntu 22.04.

**Comment by nicogodet** [comment]
Could you be more specific ?

**Comment by urabbani** [comment]
Trying to figure out how to get more information out. I have an almost fresh install of 22.04 with QGIS 3.22.47 ... When I install the plugin it it crashes at the last moment where it is suppose to enable it. 
When I open QGIS again, the plugin shows installed but not enabled, it crashes qgis again when I enable it. Its happening. Im trying different versions of the tool via zip file install. 
I have a feeling has something to do with some python error that I cant read for now coz it crashes on me.

**Comment by urabbani** [comment]
OK. I was able install and Enable Profiletool version 4.1.8. And getting this python error when enabling it:

I do know for sure if this is exact error that's causing the crash with version 4.2.2.


TypeError: setValue(self, int): argument 1 has unexpected type 'numpy.float64' 
Traceback (most recent call last):
  File "/home/umair/.local/share/QGIS/QGIS3/profiles/default/python/plugins/profiletool/profileplugin.py", line 91, in run
    self.profiletool = ProfileToolCore(self.iface,self)
  File "/home/umair/.local/share/QGIS/QGIS3/profiles/default/python/plugins/profiletool/tools/profiletool_core.py", line 90, in __init__
    self.dockwidget.changePlotLibrary( self.dockwidget.cboLibrary.currentIndex() )
  File "/home/umair/.local/share/QGIS/QGIS3/profiles/default/python/plugins/profiletool/ui/ptdockwidget.py", line 148, in changePlotLibrary
    self.addPlotWidget(self.plotlibrary)
  File "/home/umair/.local/share/QGIS/QGIS3/profiles/default/python/plugins/profiletool/ui/ptdockwidget.py", line 181, in addPlotWidget
    self.plotWdg = PlottingTool().changePlotWidget("PyQtGraph", self.frame_for_plot)
  File "/home/umair/.local/share/QGIS/QGIS3/profiles/default/python/plugins/profiletool/tools/plottingtool.py", line 94, in changePlotWidget
    plotWdg.showGrid(True,True,0.5)
  File "/home/umair/.local/share/QGIS/QGIS3/profiles/default/python/plugins/profiletool/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 340, in showGrid
    self.ctrl.gridAlphaSlider.setValue(v)
TypeError: setValue(self, int): argument 1 has unexpected type 'numpy.float64'

**Comment by nicogodet** [comment]
This is supposed to be fixed in 4.2.2

22.04 uses Python3.10 ? Could be related.

Any way, I won't spent any time trying to fix it as Profile Tool in now part of QGIS core in 3.26...
