### ISSUE TITLE
Python error on slope calculation

### ISSUE THREAD

**Issue by Cantalou15** [PANOimagen/profiletool#87]
I get a python error when I click the Height/Slope%/Slope° button to view the slope.

QGis 3.30.2 Win 10

`2023-05-10T10:42:45     WARNING    Traceback (most recent call last):
              File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 97, in 
              self.dockwidget.plotComboBox.currentIndexChanged.connect(lambda index: self.plotProfil())
              File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 235, in plotProfil
              profile["plot_x"], profile["plot_y"] = profile_func(profile)
              File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profilers.py", line 44, in slopes_pct
              x = np.array(p["l"], dtype=np.float)
              File "C:\QGIS\apps\Python39\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
              raise AttributeError("module {!r} has no attribute "
             AttributeError: module 'numpy' has no attribute 'float'
             
2023-05-10T10:42:52     WARNING    Traceback (most recent call last):
              File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 97, in 
              self.dockwidget.plotComboBox.currentIndexChanged.connect(lambda index: self.plotProfil())
              File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 235, in plotProfil
              profile["plot_x"], profile["plot_y"] = profile_func(profile)
              File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profilers.py", line 59, in slopes_deg
              x, slope_pct = slopes_pct(p)
              File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profilers.py", line 44, in slopes_pct
              x = np.array(p["l"], dtype=np.float)
              File "C:\QGIS\apps\Python39\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
              raise AttributeError("module {!r} has no attribute "
             AttributeError: module 'numpy' has no attribute 'float'
             
2023-05-10T10:47:23     WARNING    Traceback (most recent call last):
              File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 97, in 
              self.dockwidget.plotComboBox.currentIndexChanged.connect(lambda index: self.plotProfil())
              File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 235, in plotProfil
              profile["plot_x"], profile["plot_y"] = profile_func(profile)
              File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profilers.py", line 44, in slopes_pct
              x = np.array(p["l"], dtype=np.float)
              File "C:\QGIS\apps\Python39\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
              raise AttributeError("module {!r} has no attribute "
             AttributeError: module 'numpy' has no attribute 'float'
             
2023-05-10T10:51:38     WARNING    Traceback (most recent call last):
              File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 97, in 
              self.dockwidget.plotComboBox.currentIndexChanged.connect(lambda index: self.plotProfil())
              File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profiletool_core.py", line 235, in plotProfil
              profile["plot_x"], profile["plot_y"] = profile_func(profile)
              File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\profilers.py", line 44, in slopes_pct
              x = np.array(p["l"], dtype=np.float)
              File "C:\QGIS\apps\Python39\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
              raise AttributeError("module {!r} has no attribute "
             AttributeError: module 'numpy' has no attribute 'float'`

**Comment by nicogodet** [comment]
Duplicates https://github.com/PANOimagen/profiletool/issues/85
