### ISSUE TITLE
NameError: name 'os' is not defined

### ISSUE THREAD

**Issue by JaviBecerra** [PANOimagen/profiletool#9]
Reported by user @fjb80 (https://github.com/etiennesky/profiletool/issues/60):

When I try to export as a png, sag or dxf I get the following error:

NameError: name 'os' is not defined

How do I resolve this so I can export the profile?

Thanks,

**Comment by JaviBecerra** [comment]
We have not been able to reproduce your issue, but we have found a couple of apparently missing 'import os' statements in flowchart.py and plottingtool.py, will upload asap.
Could you provide the full error message (if you open the Python Console you should see the full stacktrace) to check that it is actually one of those two files that is at fault?

**Comment by fjb80** [comment]
Here's the full error:

2018-09-10T08:39:39     WARNING    Traceback (most recent call last):
              File "/Users/USERNAME/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/profiletool/ui/ptdockwidget.py", line 559, in saveAs
              self.outPNG()
              File "/Users/USERNAME/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/profiletool/ui/ptdockwidget.py", line 579, in outPNG
              PlottingTool().outPNG(self.iface, self, self.mdl, self.cboLibrary.currentText ())
              File "/Users/USERNAME/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/profiletool/tools/plottingtool.py", line 526, in outPNG
              wdg.profiletoolcore.loaddirectory = os.path.dirname(fileName)
             NameError: name 'os' is not defined

**Comment by JaviBecerra** [comment]
Hi @fjb80:
Thanks for the full trace! This should have been fixed with commit  7c98d69, we will be pushing an updated version to qgis repositories tomorrow.
If you want a quick fix before this gets published, you can manually add the line:
```import os```
to file /Users/USERNAME/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/profiletool/tools/plottingtool.py right below 'import qgis'

Regards,
Javier

**Comment by fjb80** [comment]
That did the trick as a quick fix. Thanks!
